language: python
python:
- 3.6.1
services: postgresql
env:
- DJANGO=1.11.2
before_install:
- openssl aes-256-cbc -K $encrypted_e417b2f92282_key -iv $encrypted_e417b2f92282_iv
  -in config.py.enc -out efigie/config.py -d
- openssl aes-256-cbc -K $encrypted_8f09a5331830_key -iv $encrypted_8f09a5331830_iv
  -in config.py.enc -out efigie/config.py -d
- export DJANGO_SETTINGS_MODULE=efigie.settings
- export PYTHONPATH=$HOME/builds/pcatherine/efigie
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE efigie;" -U postgres
script:
- python manage.py migrate --run-syncdb
before_deploy:
- git remote -v
deploy:
  provider: heroku
  api_key: 
  app: efigie
  on:
    repo: pcatherine/efigie
