#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.6.1

services: postgresql

env:
  - DJANGO=1.10.6

before_install:
  - export DJANGO_SETTINGS_MODULE=efigie.settings
  - export PYTHONPATH=$HOME/builds/pcatherine/efigie
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE efigie;" -U postgres

script:
  - python manage.py migrate --run-syncdb
