language: python
python:
- 3.6.1
services: postgresql
env:
- DJANGO=1.11.2
before_install:
- openssl aes-256-cbc -K $encrypted_8f09a5331830_key -iv $encrypted_8f09a5331830_iv
  -in config.py.enc -out efigie/config.py -d
- export DJANGO_SETTINGS_MODULE=efigie.settings
- export PYTHONPATH=$HOME/builds/pcatherine/efigie
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE efigie;" -U postgres
script:
- python manage.py migrate --run-syncdb
deploy:
  provider: heroku
  api_key:
    secure: nASky2+MDooYGFoe8g6SuLlT8uECx48+KUeKJeG78Gn1HgpHqyeCNCkPQlqF5N3iAsfmQio1E18fGcAF/nZZH+/aCOJn7rpd7KpVH1jO9IqPhlRy207n/lgOpgG+HKKAkK6Xyf1vI6G5bG+UG0pMFfQejNnwzokx+1eS3sXTgtpPEZUC+KaX4HVhEqUP63ckQkVhOrUy4SIkn1OPSxkCKgu7wj5YMxT1BXlSfI1xppaiezzdFvQocXMoJKqDmli+d+pFhyZDtRDlzZEEmQTQc34GOl1dwmxSGFmDAicvGB2Y+hfuhlfdt9jZmb5GLSZdF9pl3s1U+UmlhltzNpfjitlqI8TGVUwXqsSMNyPgnmboruYCCs7VbyqK8FHMQBPM1Gx112q1EKFBIA3bSpbWGPXaK7TSfXMSzROVKsH3eX43xnNDrXC2JM+YuR9z5De49vBU10lr20nMwCwTNjc0zVJCfGwhxgKJIIlG39GiwX46oq5sMuuxay8Ap6kvHW2tOl0UEIYl+QGpRV/yf3IcDi+PnfjkfXEMJjmdOZjHBWm7S0Hie/ALGZ1cAc92RdPj60XYOnz6u3Fww9huiCJu5oyFKAFbp37TVaCQbOYd2P1nWLiGJgcBccVaXpzJNr2Cp9z3EGLXs8MEE0/jF1YAveimYffkfoTxnvopaF/ao+o=
  app: efigie
  on:
    repo: pcatherine/efigie