language: python
python:
- 3.6.1
services: postgresql
env:
- DJANGO=1.10.6
before_install:
- openssl aes-256-cbc -K $encrypted_e417b2f92282_key -iv $encrypted_e417b2f92282_iv -in config.py.enc -out efigie/config.py -d
- export DJANGO_SETTINGS_MODULE=efigie.settings
- export PYTHONPATH=$HOME/builds/pcatherine/efigie
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
- pip install django==$DJANGO --quiet
- pip install psycopg2 --quiet
before_script:
- psql -c "CREATE DATABASE efigie;" -U postgres
script:
- python manage.py migrate --run-syncdb
deploy:
  provider: heroku
  api_key:
    secure: LTwCByke7vEqTKTjgeAy+Aia3e5/efI9KpocmCDo5FP8UKzdNmJAS1ICdV2zq8FzAYc75SMVx6Sum81qJiIUJIdKtmGu3RY7T0GrPP0wigvfo0EsrA444Mi3QPLHXIQdpGjHFRrLeGL0gsPfD6peFU+XobMl9E1gZAkQ/oZ/OD8yr1mmffqJINKiE7bmZGv1bAJEArjzhuPAifn1LsWChEMH/W6ddBwtP6WDifv/EKMnry/KZ55tfwNVKLlOenDcUETMUoZkjcqW8PolhlhEW438Zz5QakkzcwKggyTDSQvhPMRLqW3APcQDoK8hvEJZItzCWMiG7l54uPxstH9rx4I6olhD0rS8314rVZujFsFjOGMBE+cjqG8gxnZ6rPBBzb94GBh3CTKmq53MzP6yufjrj5g0PTdlL+Lf/dm1gJfsoeVYb+mfuhMJA58kJWcStEX+3gmJzL7pPyMpD9N6RiX/qzcIA3XDkXtyDUSFjDwWKed/jmiUOb5YJLXYM1Ea31vTyIBgFYXYNfvo04/u1djvv9Dh2UXYc7UR2jWv8hn48Qt5heWlpls1aNjN1L5QeM+DAg5kRta4a51GVvJ7TQ1+ztYE58bO/a+piuZRys+I/5JYAUVEh9F+szAVQBIJeNOvsrc1wDCPyMHPlvoSRP/yfX1YmocwSHMAVLgXvVA=
  app: efigie
  on:
    repo: pcatherine/efigie
  run:
    - "python manege.py makemigrations"
    - "python manege.py migrate"
